Repository prgrms-fe-devcourse/NFE1_2_3_Quote, pull requests merged in 2024-10, with the labels that each got.

#7 Style : 헤더 구조 구현 완료
  frontend/src/assets/icons/darkMode_button.svg
  frontend/src/assets/icons/lightMode_button.svg
  frontend/src/assets/images/profile.png
  frontend/src/assets/images/quoteLogo.png
  frontend/src/components/Header/Header.tsx
  frontend/src/layouts/MainLayout.tsx
Labels: 🎨Style

#9 🎨 Style: 회원가입, 로그인 페이지 스타일 적용 #1
  frontend/src/pages/LogInPage/LoginPage.tsx
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
Labels: 🎨Style

#12 🎨 Style: 글 작성 페이지 스타일 적용 #3
  frontend/src/pages/PostCreate/components/CreatePost.tsx
Labels: 🎨Style

#13 🎨 Style: 마이페이지 스타일 적용
  frontend/src/components/Header/Header.tsx
  frontend/src/layouts/MainLayout.tsx
  frontend/src/pages/MyPages/MyPage.tsx
Labels: 🎨Style

#16 ✨ Feat : 글쓰기 버튼 구현
  frontend/src/components/Header/Header.tsx
  frontend/src/components/WriteButton/WriteButton.tsx
  frontend/src/pages/MainPage/MainPage.tsx
Labels: ✨Feat

#18 ✨ Feat : 글 작성 페이지 스타일 수정과 컴포넌트 분리
  frontend/src/pages/PostCreate/CreatePost.tsx
  frontend/src/pages/PostCreate/components/CategorySelect.tsx
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/routes/Router.tsx
Labels: 🎨Style

#26 ✨ Feat: 회원가입 완료 후 알림 띄우고 로그인 페이지로 이동 #10
  frontend/src/pages/LogInPage/apis/login.ts
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/LogInPage/hooks/useLogin.ts
  frontend/src/pages/SignUpPage/apis/signUp.ts
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
  frontend/src/pages/SignUpPage/hooks/useSignUp.ts
Labels: ✨Feat

#27 🎨 Style : 다른 유저 페이지 스타일 적용
  frontend/src/pages/UserPages/UserPage.tsx
  frontend/src/pages/UserPages/components/PostCard.tsx
  frontend/src/routes/Router.tsx
  package-lock.json
Labels: 🎨Style

#29 ✨ Feat: 글 작성 페이지 구현
  frontend/src/pages/PostCreate/CreatePost.tsx
  frontend/src/pages/PostCreate/apis/api.ts
  frontend/src/pages/PostCreate/components/CancelPopUp.tsx
  frontend/src/pages/PostCreate/components/CategorySelect.tsx
  frontend/src/pages/PostCreate/components/CreatePost.tsx
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
Labels: ✨Feat

#31 ✨ Feat: 로그인 시 토큰 저장하고 로그아웃 시 토큰 삭제 #23
  frontend/src/pages/LogInPage/apis/login.ts
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/LogInPage/hooks/useLogin.ts
  frontend/src/pages/LogInPage/store/authStore.ts
Labels: ✨Feat

#33 ✨ Feat: 로그아웃 모달창 기능 및 스타일 구현 #30
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/LogInPage/components/LogoutModal.tsx
Labels: ✨Feat, 🎨Style

#34 ✨ Feat: 헤더 기능 구현
  frontend/src/components/Header/Header.tsx
Labels: ✨Feat

#38 ✨Feat : 메인페이지 구현 완료 #22
  frontend/src/pages/LogInPage/components/LogoutModal.tsx
  frontend/src/pages/LogInPage/store/authStore.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/apis/.gitkeep
  frontend/src/pages/MainPage/apis/bookmarkApi.ts
  frontend/src/pages/MainPage/apis/postApi.ts
  frontend/src/pages/MainPage/apis/userApi.ts
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MainPage/components/Search.tsx
  frontend/src/pages/MainPage/hooks/.gitkeep
  frontend/src/pages/MainPage/hooks/useGetPostData.ts
  frontend/src/types/Types.ts
Labels: ✨Feat

#40 ✨ Feat: 회원가입, 로그인 비밀번호 숨김/보이기 처리 #36
  frontend/src/assets/icons/pwd_hideEye.svg
  frontend/src/assets/icons/pwd_showEye.svg
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
Labels: ✨Feat, 🎨Style

#43 ✨Feat: 백엔드 코드 통합
  backend/.eslintrc.js
  backend/.gitignore
  backend/.prettierrc
  backend/README.md
  backend/nest-cli.json
  backend/package-lock.json
  backend/package.json
  backend/src/app.controller.ts
  backend/src/app.module.ts
  backend/src/app.service.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/login.request.dto.ts
  backend/src/auth/jwt/jwt.guard.ts
  backend/src/auth/jwt/jwt.payload.ts
  backend/src/auth/jwt/jwt.strategy.ts
  backend/src/comments/comments.controller.ts
  backend/src/comments/comments.module.ts
  backend/src/comments/comments.service.ts
  backend/src/comments/dto/comments.create.dto.ts
  backend/src/comments/repository/comments.repository.ts
  backend/src/comments/schemas/comments.schema.ts
  backend/src/common/decorators/user.decorator.ts
  backend/src/common/exceptions/http-exception.filter.ts
  backend/src/common/interceptors/success.interceptor.ts
  backend/src/common/middlewares/logger/logger.middleware.spec.ts
  backend/src/common/middlewares/logger/logger.middleware.ts
  backend/src/common/utils/multer.options.ts
  backend/src/main.ts
  backend/src/pipes/NotFloat.pipe.ts
  backend/src/pipes/positiveint.pipe.ts
  backend/src/posts/aws.service.ts
  backend/src/posts/dto/post.request.dto.ts
  backend/src/posts/dto/post.response.dto.ts
  backend/src/posts/dto/post.save.dao.ts
  backend/src/posts/posts.controller.ts
  backend/src/posts/posts.module.ts
  backend/src/posts/posts.service.ts
  backend/src/posts/repository/posts.repository.ts
  backend/src/posts/schemas/post.schema.ts
  backend/src/users/dto/user.readOnly.dto.ts
  backend/src/users/dto/user.response.dto.ts
  backend/src/users/dto/users.request.dto.ts
  backend/src/users/repository/users.repository.ts
  backend/src/users/schemas/user.schema.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.module.ts
  backend/src/users/users.service.ts
  backend/test/app.e2e-spec.ts
  backend/test/jest-e2e.json
  backend/tsconfig.build.json
  backend/tsconfig.json
Labels: ✨Feat

#47 ✨Feat : 마이페이지 구현 완료 #28
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/MyPages/apis/bookmarkApi.ts
  frontend/src/pages/MyPages/apis/mypage.ts
  frontend/src/pages/MyPages/components/DeleteModal.tsx
  frontend/src/pages/MyPages/components/PostCard.tsx
  frontend/src/pages/MyPages/components/ProfileEditModal.tsx
  frontend/src/styles/theme.ts
Labels: ✨Feat

#49 🔧 Fix: 삭제 api 작동안하는 문제 해결 #44
  backend/src/posts/dto/post.response.dto.ts
  backend/src/posts/posts.controller.ts
  backend/src/posts/posts.service.ts
  backend/src/posts/repository/posts.repository.ts
  backend/src/posts/schemas/post.schema.ts
Labels: 🔧Fix

#51 ✨Feat : 헤더 프로필 이미지 구현 완료 #48
  frontend/src/components/Header/Header.tsx
Labels: ✨Feat

#52 ✨ Feat: 글 상세 페이지 구현 및 스타일 적용
  frontend/src/assets/icons/quote_end.svg
  frontend/src/assets/icons/quote_start.svg
  frontend/src/pages/PostCreate/apis/api.ts
  frontend/src/pages/PostDetail/PostDetailPage.tsx
  frontend/src/pages/PostDetail/apis/postDetailApi.ts
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/PostModify/PostModifyPage.tsx
  frontend/src/pages/PostModify/components/PostModifyForm.tsx
  frontend/src/routes/Router.tsx
Labels: ✨Feat, 🎨Style

#54 ✨Feat : 메인페이지 개선 #39
  frontend/index.html
  frontend/public/favicon.svg
  frontend/public/vite.svg
  frontend/src/components/Spinner/Spinner.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/apis/bookmarkApi.ts
  frontend/src/pages/MainPage/apis/postApi.ts
  frontend/src/pages/MainPage/apis/userApi.ts
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MainPage/components/Search.tsx
  frontend/src/pages/MainPage/hooks/useBookmarkMutation.ts
Labels: ♻️Refactor

#56 ✨ Feat : 닉네임 중복 검증 api 추가 #50
  backend/src/posts/repository/posts.repository.ts
  backend/src/users/repository/users.repository.ts
  backend/src/users/users.controller.ts
  backend/src/users/users.service.ts
Labels: ✨Feat

#60 [Style, Feat] 카카오 회원가입/로그인 버튼 스타일 적용, 회원가입 닉네임 글자수 체크
  frontend/src/assets/icons/kakaoIcon.svg
  frontend/src/assets/icons/signUp_email.svg
  frontend/src/layouts/MainLayout.tsx
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/SignUpPage/SignUpPage.tsx
  frontend/src/pages/SignUpPage/apis/signUp.ts
  frontend/src/pages/SignUpPage/components/KakaoBtn.tsx
  frontend/src/pages/SignUpPage/components/Redirect.tsx
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
  frontend/src/pages/SignUpPage/components/SignUpRoutePage.tsx
  frontend/src/routes/Router.tsx
Labels: ✨Feat, 🎨Style

#62 🎨 Style : 메인페이지 스타일 개선 #59
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MainPage/components/Search.tsx
Labels: 🎨Style

#63 ✨ Feat: 소셜 로그인 구현 (카카오) #41
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/oauth/kakao/kakao.guard.ts
  backend/src/auth/oauth/kakao/kakao.strategy.ts
  backend/src/auth/oauth/kakao/kakao.userInfo.dto.ts
  backend/src/posts/repository/posts.repository.ts
  backend/src/users/schemas/user.schema.ts
  package-lock.json
  package.json
Labels: ✨Feat

#66 ✨ Feat: 404페이지 구현 완료 #65
  frontend/src/assets/images/notFound_darkMode.png
  frontend/src/assets/images/notFound_lightMode.png
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/NotFoundPage/NotFoundPage.tsx
  frontend/src/styles/theme.ts
Labels: ✨Feat

#70 ♻Refactor: 마이페이지 리팩토링 완료 #68
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/MyPages/apis/bookmarkApi.ts
  frontend/src/pages/MyPages/apis/mypage.ts
  frontend/src/pages/MyPages/components/PostCard.tsx
  frontend/src/pages/MyPages/components/ProfileEditModal.tsx
  frontend/src/pages/MyPages/hooks/useBookmark.ts
  frontend/src/pages/MyPages/hooks/useMyPage.ts
  frontend/src/pages/MyPages/hooks/useProfileEdit.ts
Labels: ♻️Refactor

#73 ♻Refactor: 패키지 삭제 및 소셜로그인 리턴값 수정
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  package-lock.json
  package.json
Labels: ♻️Refactor

#74 ♻️ Refactor : 포스트 관련 페이지들 리팩토링
  frontend/src/assets/icons/quote_end.svg
  frontend/src/assets/icons/quote_start.svg
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/pages/PostCreate/hooks/useCreatePost.ts
  frontend/src/pages/PostDetail/PostDetailPage.tsx
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/PostDetail/components/ScrollToTop.tsx
  frontend/src/pages/PostDetail/hooks/useBookmark.ts
  frontend/src/pages/PostDetail/hooks/useDeletePost.ts
  frontend/src/pages/PostDetail/hooks/useGetLoggedInUser.ts
  frontend/src/pages/PostDetail/hooks/useGetPostInfo.ts
  frontend/src/pages/PostModify/components/PostModifyForm.tsx
  frontend/src/pages/PostModify/hooks/useModifyPost.ts
Labels: ♻️Refactor

#76 ♻️ Refactor : 메인페이지 리팩토링
  frontend/src/assets/images/.gitkeep
  frontend/src/components/.gitkeep
  frontend/src/components/AlertPopUp/AlertPopUp.tsx
  frontend/src/pages/.gitkeep
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/apis/userApi.ts
  frontend/src/pages/MainPage/components/CategoryMark.tsx
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MainPage/components/Search.tsx
  frontend/src/pages/MainPage/hooks/useBookmarkMutation.ts
  frontend/src/routes/Router.tsx
  frontend/src/styles/GlobalStyle.ts
  frontend/src/styles/theme.ts
  frontend/src/types/.gitkeep
Labels: ♻️Refactor

#79 ♻️ Refactor: 소셜 로그인 REST 방식으로 변경
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
Labels: ♻️Refactor

#81 ✨ Feat: 댓글 CRUD
  backend/src/comments/comments.controller.ts
  backend/src/comments/comments.module.ts
  backend/src/comments/comments.service.ts
  backend/src/comments/dto/comments.response.dto.ts
  backend/src/comments/repository/comments.repository.ts
  backend/src/comments/schemas/comments.schema.ts
  backend/src/posts/posts.service.ts
  backend/src/posts/repository/posts.repository.ts
Labels: ✨Feat

#84 ♻️ Refactor: 포스트 관련 페이지 리팩토링
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MyPages/hooks/useMyPage.ts
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/PostModify/components/PostModifyForm.tsx
  frontend/src/pages/PostModify/hooks/useModifyPost.ts
Labels: ♻️Refactor

#86 ✨ Feat: 댓글 기능 구현 #82
  frontend/src/pages/PostDetail/PostDetailPage.tsx
  frontend/src/pages/PostDetail/apis/postCommentApi.ts
  frontend/src/pages/PostDetail/components/Comment.tsx
  frontend/src/pages/PostDetail/components/PostComment.tsx
  frontend/src/pages/PostDetail/components/PostCommentPopUp.tsx
  frontend/src/pages/PostDetail/hooks/usePostComment.ts
  frontend/src/styles/theme.ts
  frontend/src/types/Types.ts
Labels: ✨Feat

#87 ✨Feat : 다른 유저 페이지 기능 구현 완료 #71
  frontend/src/components/Header/Header.tsx
  frontend/src/pages/UserPages/UserPage.tsx
  frontend/src/pages/UserPages/apis/userpage.ts
  frontend/src/pages/UserPages/components/PostCard.tsx
  frontend/src/pages/UserPages/hooks/useBookmark.ts
  frontend/src/pages/UserPages/hooks/useUserPage.ts
  frontend/src/types/Types.ts
Labels: ✨Feat, ♻️Refactor

#88 ♻️ Refactor: 작성 취소 버튼 이후 루트 수정
  frontend/src/components/WriteButton/WriteButton.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/PostCreate/components/CancelPopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
Labels: ♻️Refactor

#89 ♻️ Refactor: 로그인, 회원가입 페이지 리팩토링
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/LogInPage/hooks/useLogin.ts
  frontend/src/pages/SignUpPage/components/PwdInput.tsx
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
  frontend/src/pages/SignUpPage/hooks/useSignUp.ts
Labels: ♻️Refactor

#90 ♻️ Refactor: 포스트 관련 페이지 리팩토링과 글 상세페이지 스타일 수정
  frontend/src/pages/PostCreate/components/CancelPopUp.tsx
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/PostDetail/hooks/useDeletePost.ts
  frontend/src/pages/PostModify/components/PostModifyForm.tsx
Labels: 🎨Style, ♻️Refactor

#92 :sparkles: Feat: CI/CD 구축
  frontend/.github/workflows/cicd.yml
  frontend/Dockerfile
  frontend/tsconfig.app.tsbuildinfo
  frontend/tsconfig.node.tsbuildinfo
Labels: ✨Feat

#94 🗑️ Chore: 회원가입, 로그인 페이지 tsc -b 에러 수정
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
  frontend/src/pages/SignUpPage/components/SignUpRoutePage.tsx
Labels: 🗑️Chore

#96 ♻️ Refactor: 글 상세 페이지 댓글 리팩토링 #95
  frontend/src/pages/MainPage/apis/postApi.ts
  frontend/src/pages/MainPage/hooks/useGetPostData.ts
  frontend/src/pages/PostDetail/components/Comment.tsx
  frontend/src/pages/PostDetail/components/PostComment.tsx
  frontend/src/pages/PostDetail/components/PostCommentPopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/utils/formatTime.ts
Labels: 🎨Style, ♻️Refactor

#97 ♻️ Refactor: 마이페이지 리팩토링 #93
  frontend/src/assets/icons/profile_modify_darkMode.svg
  frontend/src/assets/icons/profile_modify_lightMode.svg
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/MyPages/components/DeleteModal.tsx
  frontend/src/pages/MyPages/components/PostCard.tsx
  frontend/src/pages/MyPages/components/ProfileEditModal.tsx
  frontend/src/pages/MyPages/hooks/useBookmark.ts
  frontend/src/pages/MyPages/hooks/useMyPage.ts
  frontend/src/pages/MyPages/hooks/useProfileEdit.ts
  frontend/src/pages/UserPages/UserPage.tsx
  frontend/src/pages/UserPages/components/PostCard.tsx
  frontend/src/pages/UserPages/hooks/useUserPage.ts
  frontend/src/styles/theme.ts
Labels: 🎨Style, ♻️Refactor

#98 🗑️ Chore: 환경변수 설정
  frontend/src/pages/MainPage/apis/postApi.ts
  frontend/src/pages/MainPage/apis/userApi.ts
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/PostCreate/apis/api.ts
  frontend/src/pages/PostDetail/apis/postDetailApi.ts
  frontend/src/pages/PostModify/apis/postModifyApi.ts
  frontend/src/pages/SignUpPage/apis/signUp.ts
  frontend/src/pages/SignUpPage/components/KakaoBtn.tsx
  frontend/src/pages/SignUpPage/components/RedirectPage.tsx
Labels: 🗑️Chore
