Repository prgrms-fe-devcourse/NFE1_2_3_Quote, pull requests merged in 2024-11, with the labels that each got.

#100 🎨 Style: 글카드 스타일 수정 #99
  frontend/src/pages/MainPage/components/PostCard.tsx
Labels: 🎨Style

#103 🔧 Fix: 글카드 수정
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MyPages/components/PostCard.tsx
  frontend/src/pages/UserPages/components/PostCard.tsx
Labels: 🔧Fix

#104 ♻️ Refactor: 마이페이지 리팩토링 #101
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/MyPages/hooks/useMyPage.ts
Labels: ♻️Refactor

#105 ♻️ Refactor: 글 상세 페이지 수정
  frontend/src/pages/PostDetail/PostDetailPage.tsx
  frontend/src/pages/PostDetail/components/PostComment.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/PostDetail/hooks/useGetPostInfo.ts
  frontend/src/pages/PostDetail/hooks/usePostComment.ts
Labels: ♻️Refactor

#107 :sparkles: Feat: post schema 수정
  backend/src/comments/repository/comments.repository.ts
  backend/src/comments/schemas/comments.schema.ts
  backend/src/posts/repository/posts.repository.ts
  backend/src/posts/schemas/post.schema.ts
Labels: ✨Feat

#109 🎨 Style : 알림 팝업 리팩토링 #108
  frontend/src/components/WriteButton/WriteButton.tsx
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/LogInPage/hooks/useLogin.ts
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/PostDetail/hooks/useDeletePost.ts
  frontend/src/pages/PostModify/components/PostModifyForm.tsx
  frontend/src/pages/PostModify/hooks/useModifyPost.ts
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
Labels: 🎨Style

#110 🔧 Fix : 메인페이지 및 글카드 개선 #102
  frontend/src/assets/icons/comment.svg
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MyPages/components/PostCard.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/UserPages/components/PostCard.tsx
  frontend/src/types/Types.ts
Labels: 🔧Fix

#112 🎨 Style: 글작성 페이지 디자인 수정 #111
  frontend/src/assets/icons/cancelBtn.svg
  frontend/src/pages/PostCreate/components/CancelPopUp.tsx
  frontend/src/pages/PostCreate/components/CategorySelect.tsx
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
Labels: 🎨Style

#114 ✨ Feat : 스크롤 버튼 추가 및 스타일 수정 #113
  frontend/src/assets/icons/scrollUp_button.svg
  frontend/src/components/ScrollButton/ScrollButton.tsx
  frontend/src/components/WriteButton/WriteButton.tsx
  frontend/src/layouts/MainLayout.tsx
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/pages/UserPages/UserPage.tsx
Labels: ✨Feat

#116 🎨 Style: 알림 팝업 리팩토링 #115
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/pages/PostCreate/hooks/useCreatePost.ts
  frontend/src/pages/UserPages/UserPage.tsx
Labels: 🎨Style

#117 🎨 Style: 글 상세 페이지 스타일 수정
  frontend/src/pages/PostDetail/components/Comment.tsx
  frontend/src/pages/PostDetail/components/PostComment.tsx
  frontend/src/pages/PostDetail/components/PostCommentPopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
Labels: 🎨Style

#118 ✨ Feat : 인용글 복사 기능 추가 및 스타일 수정
  frontend/src/components/Tooltip/Tooltip.tsx
  frontend/src/pages/LogInPage/components/LogoutModal.tsx
  frontend/src/pages/MyPages/components/DeleteModal.tsx
  frontend/src/pages/MyPages/components/ProfileEditModal.tsx
  frontend/src/pages/PostCreate/components/CancelPopUp.tsx
  frontend/src/pages/PostDetail/components/PostCommentPopUp.tsx
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
  frontend/src/pages/PostDetail/components/PostDetail.tsx
Labels: ✨Feat

#119 🎨 Style: 마이페이지 프로필 버튼 그림자 지우기
  frontend/src/pages/MyPages/MyPage.tsx
Labels: 🎨Style

#120 🔧 Fix: 스크롤 문제 해결
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
  frontend/src/pages/PostModify/components/PostModifyForm.tsx
Labels: 🔧Fix

#122 Feat : 팝업 기능 수정
  frontend/src/pages/MyPages/components/DeleteModal.tsx
  frontend/src/pages/MyPages/hooks/useProfileEdit.ts
  frontend/src/pages/PostCreate/components/CancelPopUp.tsx
  frontend/src/pages/PostDetail/components/PostDeletePopUp.tsx
Labels: ✨Feat

#123 🎨 Style : 댓글 닉네임 스타일 수정
  frontend/src/pages/PostDetail/components/Comment.tsx
  frontend/src/pages/PostDetail/components/PostComment.tsx
Labels: 🎨Style

#124 ♻️ Refactor: 글 작성 페이지 플레이스 홀더 수정
  frontend/src/pages/PostCreate/components/CreatePostForm.tsx
Labels: ♻️Refactor

#125 🗑️Chore: 카카오 로그인 navigate 수정
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/SignUpPage/components/RedirectPage.tsx
  frontend/src/pages/SignUpPage/components/SignUpForm.tsx
Labels: 🗑️Chore

#127 :sparkles: Feat:띄어쓰기 없애고 검색, 포스트 삭제 시 댓글 삭제
  backend/src/auth/auth.service.ts
  backend/src/auth/oauth/kakao/kakao.strategy.ts
  backend/src/posts/repository/posts.repository.ts
  frontend/tsconfig.app.tsbuildinfo
Labels: ✨Feat

#128 🎨 Style: 마이페이지/다른유저페이지 스타일 수정 #111
  frontend/src/pages/MainPage/components/PostCard.tsx
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/MyPages/components/PostCard.tsx
  frontend/src/pages/MyPages/components/ProfileEditModal.tsx
  frontend/src/pages/UserPages/UserPage.tsx
  frontend/src/pages/UserPages/components/PostCard.tsx
Labels: 🎨Style

#129 ♻️ Refactor: 팝업 기능 리팩토링
  frontend/src/components/AlertPopUp/AlertPopUp.tsx
  frontend/src/pages/LogInPage/components/LoginForm.tsx
  frontend/src/pages/MainPage/MainPage.tsx
  frontend/src/pages/MyPages/MyPage.tsx
  frontend/src/pages/MyPages/hooks/useMyPage.ts
  frontend/src/pages/PostDetail/components/PostDetail.tsx
  frontend/src/pages/SignUpPage/components/RedirectPage.tsx
Labels: ♻️Refactor

#130 📝 Docs : README 업데이트
  README.md
Labels: 📝Docs

#131 📝Docs : README 업데이트
  README.md
Labels: 📝Docs
